# Generated by Django 3.1.3 on 2020-11-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-slug'],
            },
        ),
    ]
